openapi: 3.0.0
x-stoplight:
  id: 79ufakk1ygzmg
info:
  title: ATS API Reference
  version: '2020-09-17'
  description: |-
    The Finch ATS (Applicant Tracking System) API provides a unified way to connect to a multitude of ATS systems. The API requires an access token issued by Finch.

    To enable access to the ATS API, please reach out to your Finch representative.

    ATS products are specified by the product parameter, a space-separated list of products that your application requests from an employer authenticating through Finch Connect. Valid product names areâ€”

    - `candidates`: Read candidate data
    - `applications`: Read detailed application data for candidates
    - `jobs`: Read job posting data, as well as existing stages of the job pipeline
    - `offers`: Read details about offers managed through the ATS
servers:
  - url: 'https://api.tryfinch.com'
paths:
  /ats/candidates:
    get:
      summary: List Candidates
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  paging:
                    $ref: ../employer/openapi.yaml#/components/schemas/Paging
                  candidates:
                    type: array
                    items:
                      $ref: '#/components/schemas/Candidate'
              examples:
                success:
                  value:
                    paging:
                      count: 0
                      offset: 0
                    candidates:
                      - id: 'e5806a14-ca47-4538-a9bf-51639efc676e  '
                        first_name: John
                        last_name: Smith
                        full_name: John Smith
                        emails:
                          - data: john@example.com
                            type: personal
                        phone_numbers:
                          - data: '5555555555'
                            type: personal
                        addresses:
                          - line1: 12 Oak Street
                            line2: null
                            city: Oakland
                            state: CA
                            postal_code: null
                            country: US
                        created_at: '2019-08-24T14:15:22Z'
                        last_activity_at: '2019-08-24T14:15:22Z'
                        application_ids:
                          - c0210513-e8d5-4817-a46c-85dfaaf5f406
      operationId: get-ats-candidate
      description: Gets all of an organization's candidates. A candidate represents an individual associated with one or more applications.
      parameters:
        - $ref: ../employer/openapi.yaml#/components/parameters/API-Version
        - $ref: ../employer/openapi.yaml#/components/parameters/Content-Type
        - schema:
            type: integer
          in: query
          name: limit
          description: Number of candidates to return (defaults to all)
        - schema:
            type: integer
            default: 0
          in: query
          name: offset
          description: Index to start from (defaults to 0)
    parameters: []
  '/ats/candidates/{candidate_id}':
    parameters:
      - schema:
          type: string
        name: candidate_id
        in: path
        required: true
    get:
      summary: Retrieve Candidate
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Candidate'
              examples:
                success:
                  value:
                    id: 'e5806a14-ca47-4538-a9bf-51639efc676e  '
                    first_name: John
                    last_name: Smith
                    full_name: John Smith
                    emails:
                      - data: john@example.com
                        type: personal
                    phone_numbers:
                      - data: '5555555555'
                        type: personal
                    addresses:
                      - line1: 12 Oak Street
                        line2: null
                        city: Oakland
                        state: CA
                        postal_code: null
                        country: US
                    created_at: '2019-08-24T14:15:22Z'
                    last_activity_at: '2019-08-24T14:15:22Z'
                    application_ids:
                      - c0210513-e8d5-4817-a46c-85dfaaf5f406
      operationId: get-ats-candidates-candidate_id
      description: Gets a candidate from an organization. A candidate represents an individual associated with one or more applications.
      parameters:
        - $ref: ../employer/openapi.yaml#/components/parameters/API-Version
        - $ref: ../employer/openapi.yaml#/components/parameters/Content-Type
  /ats/applications:
    get:
      summary: List Applications
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  paging:
                    $ref: ../employer/openapi.yaml#/components/schemas/Paging
                  applications:
                    type: array
                    items:
                      $ref: '#/components/schemas/Application'
              examples:
                success:
                  value:
                    paging:
                      count: 0
                      offset: 0
                    applications:
                      - id: 497f6eca-6276-4993-bfeb-53cbbbba6f09
                        candidate_id: 2f28f791-f0fd-4155-a356-c24e996beeda
                        job_id: 453bd7d7-5355-4d6d-a38e-d9e7eb218c3f
                        offer_id: d5a7a5b7-a4a3-49e7-9c69-b44d2cbe15cf
                        stage:
                          id: 497f6eca-6276-4993-bfeb-53cbbbba6f07
                          job_id: 453bd7d7-5355-4d6d-a38e-d9e7eb218c3f
                          name: string
                        rejected_at: '2019-08-24T14:15:22Z'
                        rejected_reason:
                          text: string
      operationId: get-ats-applications
      description: Gets all of an organization's applications.
      parameters:
        - $ref: ../employer/openapi.yaml#/components/parameters/API-Version
        - $ref: ../employer/openapi.yaml#/components/parameters/Content-Type
        - schema:
            type: integer
          in: query
          name: limit
          description: Number of applications to return (defaults to all)
        - schema:
            type: integer
            default: 0
          in: query
          name: offset
          description: Index to start from (defaults to 0)
  '/ats/applications/{application_id}':
    parameters:
      - schema:
          type: string
        name: application_id
        in: path
        required: true
    get:
      summary: Retrieve Application
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Application'
              examples:
                example-1:
                  value:
                    id: 497f6eca-6276-4993-bfeb-53cbbbba6f18
                    candidate_id: 2f28f791-f0fd-4155-a356-c24e996beeda
                    job_id: 453bd7d7-5355-4d6d-a38e-d9e7eb218c3f
                    offer_id: d5a7a5b7-a4a3-49e7-9c69-b44d2cbe15cf
                    stage:
                      id: bf25a12f-4544-4b77-a0c9-5726e16b7505
                      job_id: null
                      name: Phone Screen
                    rejected_at: '2019-08-24T14:15:22Z'
                    rejected_reason:
                      text: Underqualified
      operationId: get-ats-applications-application_id
      description: Gets an application from an organization.
      parameters:
        - $ref: ../employer/openapi.yaml#/components/parameters/API-Version
        - $ref: ../employer/openapi.yaml#/components/parameters/Content-Type
  /ats/jobs:
    get:
      summary: List Jobs
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  paging:
                    $ref: ../employer/openapi.yaml#/components/schemas/Paging
                  jobs:
                    type: array
                    items:
                      $ref: '#/components/schemas/Job'
              examples:
                success:
                  value:
                    paging:
                      count: 0
                      offset: 0
                    jobs:
                      - id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
                        name: Office Manager
                        status: open
                        department:
                          name: People
                        created_at: '2019-08-24T14:15:22Z'
                        closed_at: '2019-08-24T14:15:22Z'
                        hiring_team:
                          hiring_managers:
                            - name: Michael Glen
                          recruiters:
                            - name: Chris Pine
      operationId: get-ats-jobs
      description: Gets all of an organization's jobs.
      parameters:
        - $ref: ../employer/openapi.yaml#/components/parameters/API-Version
        - $ref: ../employer/openapi.yaml#/components/parameters/Content-Type
        - schema:
            type: integer
          in: query
          name: limit
          description: Number of jobs to return (defaults to all)
        - schema:
            type: integer
            default: 0
          in: query
          name: offset
          description: Index to start from (defaults to 0)
  '/ats/jobs/{job_id}':
    parameters:
      - schema:
          type: string
        name: job_id
        in: path
        required: true
    get:
      summary: Retrieve Job
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'
              examples:
                success:
                  value:
                    id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
                    name: Office Manager
                    status: open
                    department:
                      name: People
                    created_at: '2019-08-24T14:15:22Z'
                    closed_at: '2019-08-24T14:15:22Z'
                    hiring_team:
                      hiring_managers:
                        - name: Michael Glen
                      recruiters:
                        - name: Chris Pine
      operationId: get-ats-jobs-job_id
      description: Gets a job from an organization.
      parameters:
        - $ref: ../employer/openapi.yaml#/components/parameters/API-Version
        - $ref: ../employer/openapi.yaml#/components/parameters/Content-Type
  /ats/stages:
    get:
      summary: List Stages
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Stage'
              examples:
                Success:
                  value:
                    - id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
                      job_id: null
                      name: Phone Screen
      operationId: get-ats-stages
      description: 'Get all job stages for an organization. Depending on the system, some jobs may have stages specific to that job. Other job stages may apply broadly to all jobs in the system. Use the `job_id` to determine whether a job applies specifically to a job.'
      parameters:
        - $ref: ../employer/openapi.yaml#/components/parameters/API-Version
        - $ref: ../employer/openapi.yaml#/components/parameters/Content-Type
  /ats/offers:
    get:
      summary: List Offers
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  paging:
                    $ref: ../employer/openapi.yaml#/components/schemas/Paging
                  offers:
                    type: array
                    items:
                      $ref: '#/components/schemas/Offer'
              examples:
                example-1:
                  value:
                    paging:
                      count: 0
                      offset: 0
                    offers:
                      - id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
                        application_id: 48ac72d0-a829-4896-a067-dcb1c2b0f30c
                        candidate_id: 2f28f791-f0fd-4155-a356-c24e996beeda
                        job_id: 453bd7d7-5355-4d6d-a38e-d9e7eb218c3f
                        created_at: '2019-08-24T14:15:22Z'
                        updated_at: '2019-08-24T14:15:22Z'
                        status: signed
      operationId: get-ats-offers
      description: Get all offers put out by an organization.
      parameters:
        - $ref: ../employer/openapi.yaml#/components/parameters/API-Version
        - $ref: ../employer/openapi.yaml#/components/parameters/Content-Type
        - schema:
            type: integer
          in: query
          name: limit
          description: Number of offers to return (defaults to all)
        - schema:
            type: integer
            default: 0
          in: query
          name: offset
          description: Index to start from (defaults to 0)
  '/ats/offers/{offer_id}':
    parameters:
      - schema:
          type: string
        name: offer_id
        in: path
        required: true
    get:
      summary: Retrieve Offer
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Offer'
              examples:
                success:
                  value:
                    id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
                    application_id: 48ac72d0-a829-4896-a067-dcb1c2b0f30c
                    candidate_id: 2f28f791-f0fd-4155-a356-c24e996beeda
                    job_id: 453bd7d7-5355-4d6d-a38e-d9e7eb218c3f
                    created_at: '2019-08-24T14:15:22Z'
                    updated_at: '2019-08-24T14:15:22Z'
                    status: signed
      operationId: get-ats-offers-offer_id
      description: Get a single offer from an organization.
      parameters:
        - $ref: ../employer/openapi.yaml#/components/parameters/API-Version
        - $ref: ../employer/openapi.yaml#/components/parameters/Content-Type
components:
  schemas:
    Candidate:
      title: Candidate
      x-stoplight:
        id: 07azupxijhrvq
      type: object
      description: A candidate represents an individual associated with one or more applications.
      x-examples:
        success:
          id: 'e5806a14-ca47-4538-a9bf-51639efc676e  '
          first_name: John
          last_name: Smith
          full_name: John Smith
          emails:
            - data: john@example.com
              type: personal
          phone_numbers:
            - data: '5555555555'
              type: personal
          created_at: '2019-08-24T14:15:22Z'
          last_activity_at: '2019-08-24T14:15:22Z'
          application_ids:
            - c0210513-e8d5-4817-a46c-85dfaaf5f406
      properties:
        id:
          type: string
        first_name:
          type: string
          nullable: true
        last_name:
          type: string
          nullable: true
        full_name:
          type: string
          nullable: true
        emails:
          type: array
          items:
            type: object
            properties:
              data:
                type: string
                nullable: true
              type:
                type: string
                nullable: true
        phone_numbers:
          type: array
          items:
            type: object
            properties:
              data:
                type: string
                nullable: true
              type:
                type: string
                nullable: true
        created_at:
          type: string
          format: date-time
        last_activity_at:
          type: string
          format: date-time
        application_ids:
          type: array
          description: Array of Finch uuids corresponding to `application`s for this individual
          items:
            type: string
    Application:
      title: Application
      x-stoplight:
        id: bj615wpi71ynw
      type: object
      properties:
        id:
          type: string
          format: uuid
        candidate_id:
          type: string
          format: uuid
        job_id:
          type: string
          format: uuid
        offer_id:
          type: string
          format: uuid
          nullable: true
        stage:
          $ref: '#/components/schemas/Stage'
          nullable: true
        rejected_at:
          type: string
          format: date-time
          nullable: true
        rejected_reason:
          type: object
          nullable: true
          properties:
            text:
              type: string
              nullable: true
      x-examples:
        success:
          id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
          candidate_id: 2f28f791-f0fd-4155-a356-c24e996beeda
          job_id: 453bd7d7-5355-4d6d-a38e-d9e7eb218c3f
          offer_id: d5a7a5b7-a4a3-49e7-9c69-b44d2cbe15cf
          stage:
            id: bf25a12f-4544-4b77-a0c9-5726e16b7505
            job_id: null
            name: Phone Screen
          rejected_at: '2019-08-24T14:15:22Z'
          rejected_reason:
            text: Underqualified
    Job:
      title: Job
      x-stoplight:
        id: bfuo8aqn6gz2v
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          nullable: true
        status:
          type: string
          enum:
            - open
            - closed
            - on_hold
            - draft
            - archived
          nullable: true
        department:
          type: object
          properties:
            name:
              type: string
              nullable: true
        created_at:
          type: string
          format: date-time
          nullable: true
        closed_at:
          type: string
          format: date-time
          nullable: true
        hiring_team:
          type: object
          properties:
            hiring_managers:
              type: array
              nullable: true
              items:
                type: object
                properties:
                  name:
                    type: string
            recruiters:
              type: array
              nullable: true
              items:
                type: object
                properties:
                  name:
                    type: string
      x-examples:
        success:
          id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
          name: Office Manager
          status: open
          department:
            name: People
          created_at: '2019-08-24T14:15:22Z'
          closed_at: '2019-08-24T14:15:22Z'
          hiring_team:
            hiring_managers:
              - name: Michael Glen
            recruiters:
              - name: Chris Pine
    Stage:
      title: Stage
      x-stoplight:
        id: gul2e0glhwi6o
      type: object
      x-examples:
        example-1:
          id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
          job_id: null
          name: Phone Screen
      properties:
        id:
          type: string
          format: uuid
        job_id:
          type: string
          description: 'The job id that this stage applies to, if applicable. Not all systems enumerate stages specific to jobs.'
          format: uuid
          nullable: true
        name:
          type: string
          nullable: true
    Offer:
      title: Offer
      x-stoplight:
        id: xmnvbh0trgeo1
      type: object
      properties:
        id:
          type: string
          format: uuid
        application_id:
          type: string
          format: uuid
        candidate_id:
          type: string
          format: uuid
        job_id:
          type: string
          format: uuid
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        status:
          type: string
          enum:
            - signed
            - rejected
            - draft
            - approval-sent
            - approved
            - sent
            - sent-manually
            - opened
            - archived
      x-examples:
        success:
          id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
          application_id: 48ac72d0-a829-4896-a067-dcb1c2b0f30c
          candidate_id: 2f28f791-f0fd-4155-a356-c24e996beeda
          job_id: 453bd7d7-5355-4d6d-a38e-d9e7eb218c3f
          created_at: '2019-08-24T14:15:22Z'
          updated_at: '2019-08-24T14:15:22Z'
          status: signed
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      description: Please use an access token
security:
  - bearerAuth: []
x-internal: false
