openapi: 3.0.0
info:
  title: Management API Reference
  version: '2020-09-17'
  contact: {}
  description: >-
    The Management API provides a set of system-agnostic functionality for
    managing your Finch connections.


    [![Open in
    Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/21027137-08db0929-883d-4094-a9ce-dbf5a9bee4a4?action=collection%2Ffork&collection-url=entityId%3D21027137-08db0929-883d-4094-a9ce-dbf5a9bee4a4%26entityType%3Dcollection%26workspaceId%3D1edf19bc-e0a8-41e9-ac55-481a4b50790b)
servers:
  - url: 'https://api.tryfinch.com'
    description: ''
paths:
  /providers:
    get:
      summary: Providers
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      description: The id of the payroll provider used in Connect.
                    display_name:
                      type: string
                      description: The display name of the payroll provider.
                    products:
                      type: array
                      description: >-
                        The list of Finch products supported on this payroll
                        provider.
                      items:
                        type: string
                    category:
                      type: string
                      description: >-
                        The categroy of the integration. Possible values:
                        `hris`, `ats`
                    icon:
                      type: string
                      description: The url to the official icon of the payroll provider.
                    logo:
                      type: string
                      description: The url to the official logo of the payroll provider.
                    mfa_required:
                      type: boolean
                      description: whether MFA is required for the provider.
                    primary_color:
                      type: string
                      description: >-
                        The hex code for the primary color of the payroll
                        provider.
                    manual:
                      type: boolean
                      description: >-
                        [DEPRECATED] Whether the Finch integration with this
                        provider uses the Assisted Connect Flow by default. This
                        field is now deprecated. Please check for a `type` of
                        `assisted` in the `authentication_methods` field
                        instead.
                    authentication_methods:
                      type: array
                      description: >-
                        The list of authentication methods supported by the
                        provider.
                      items:
                        $ref: '#/components/schemas/AuthenticationMethod'
              examples:
                Success:
                  value:
                    - id: gusto
                      display_name: Gusto
                      products:
                        - company
                        - directory
                      icon: >-
                        https://finch-logos.s3.us-west-2.amazonaws.com/gustoIcon.png
                      logo: >-
                        https://finch-logos.s3.us-west-2.amazonaws.com/gustoLogo.png
                      mfa_required: true
                      primary_color: '#f45d47'
                      authentication_methods:
                        - type: api
                          benefits_support:
                            401k:
                              supported_features:
                                company_contribution: null
                                employee_deduction:
                                  - fixed
                                  - percent
                                frequencies:
                                  - one_time
                                  - every_paycheck
                                annual_maximum: false
                                catch_up: false
                                description: 401(k)
                              supported_operations:
                                company_benefits:
                                  read: not_supported_by_finch
                                  create: supported
                                  update: supported
                                  delete: not_supported_by_finch
                                individual_benefits:
                                  read: not_supported_by_finch
                                  create: supported
                                  delete: supported
                                  update: supported
                      supported_fields:
                        company:
                          id: true
                          legal_name: true
                          entity:
                            type: true
                            subtype: false
                          primary_email: true
                          primary_phone_number: true
                          ein: true
                          accounts:
                            routing_number: true
                            account_name: true
                            institution_name: true
                            account_type: true
                            account_number: true
                          departments:
                            name: true
                            parent:
                              name: true
                          locations:
                            line1: true
                            line2: true
                            city: true
                            state: true
                            postal_code: true
                            country: true
                        directory:
                          paging:
                            count: true
                            offset: true
                          individuals:
                            id: true
                            first_name: true
                            middle_name: true
                            last_name: true
                            is_active: true
                            department: null
                            manager:
                              id: true
                        individual:
                          id: true
                          first_name: true
                          middle_name: true
                          last_name: true
                          preferred_name: true
                          dob: true
                          gender: false
                          ethnicity: false
                          ssn: true
                          emails:
                            data: true
                            type: true
                          phone_numbers:
                            data: true
                            type: true
                          residence:
                            city: true
                            country: true
                            line1: true
                            line2: true
                            postal_code: true
                            state: true
                        employment:
                          id: true
                          first_name: true
                          middle_name: true
                          last_name: true
                          title: true
                          start_date: true
                          end_date: true
                          is_active: true
                          income_history: false
                          class_code: true
                          custom_fields: false
                          department:
                            name: true
                          employment:
                            type: true
                            subtype: true
                          income:
                            amount: true
                            currency: true
                            unit: true
                          location:
                            line1: true
                            line2: true
                            city: true
                            state: true
                            postal_code: true
                            country: true
                          manager: null
                        payment:
                          id: true
                          pay_date: true
                          debit_date: false
                          company_debit: true
                          gross_pay: true
                          net_pay: true
                          employer_taxes: true
                          employee_taxes: true
                          individual_ids: true
                          pay_period:
                            start_date: false
                            end_date: false
                        pay_statement:
                          paging:
                            count: true
                            offset: true
                          pay_statements:
                            individual_id: true
                            type: true
                            payment_method: true
                            total_hours: true
                            gross_pay: true
                            net_pay: true
                            earnings:
                              type: true
                              name: true
                              amount: true
                              currency: true
                            employee_deductions:
                              name: true
                              amount: true
                              type: true
                              pre_tax: true
                              currency: true
                            employer_deductions:
                              name: true
                              amount: true
                              currency: true
                            taxes:
                              type: true
                              name: true
                              employer: true
                              amount: true
                              currency: true
      operationId: get-providers
      description: Return details on all available payroll and HR systems.
      parameters:
        - $ref: '#/components/parameters/API-Version'
      security: []
  /introspect:
    get:
      summary: Introspect
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  account_id:
                    type: string
                    format: uuid
                    description: >-
                      The Finch uuid corresponding to the employer account that
                      was used to make this connection.
                  client_id:
                    type: string
                    description: >-
                      The client id of the application associated with the
                      `access_token`.
                  company_id:
                    type: string
                    description: >-
                      The Finch uuid of the company associated with the
                      `access_token`.
                  products:
                    type: array
                    description: >-
                      An array of the authorized products associated with the
                      `access_token`.
                    items:
                      type: string
                  username:
                    type: string
                    description: >-
                      The account username used for login associated with the
                      `access_token`.
                    nullable: true
                  payroll_provider_id:
                    type: string
                    description: The payroll provider associated with the `access_token`.
                  manual:
                    type: boolean
                    description: >-
                      [DEPRECATED] Whether the connection associated with the
                      `access_token` uses the Assisted Connect Flow. (`true` if
                      using Assisted Connect, `false` if connection is
                      automated). This field is now deprecated. Please look for
                      the `assisted` type in `authentication_methods` instead.
                  authentication_methods:
                    type: array
                    x-stoplight:
                      id: z411a1ngk2nvm
                    items:
                      x-stoplight:
                        id: d29u5a7sf7fps
                      type: object
                      properties:
                        type:
                          type: string
                          x-stoplight:
                            id: q4bai2n93nltm
                          description: The type of authentication method.
                          enum:
                            - credential
                            - assisted
                            - oauth
                            - api_token
                        connection_status:
                          type: object
                          x-stoplight:
                            id: 11ywt2u7zko2o
                          description: >-
                            The status of the connection for this authentication
                            method:


                            `pending` - [`assisted` only] This employer has
                            created a token, and we are waiting for access to
                            its provider <br>

                            `processing` - [`assisted` only] We have received an
                            invitation from this employer's provider with the
                            correct permissions and are in the process of
                            pulling their data for the first time <br>

                            `connected` - This connection is working as expected
                            <br>

                            `reauth` - This employer needs to re-authenticate
                            <br>

                            `error_no_accout_setup` - [`assisted` only] This
                            employer has created a token, but we have not
                            received an invitation to its system. Please
                            instruct the employer to follow the instructions in
                            Finch Connect to add Finch as a third-party admin
                            <br>

                            `error_permissions` - [`assisted` only] This
                            employer has added Finch successfully, but with
                            improper permissions. Please instruct the employer
                            to re-add Finch following the instructions in Finch
                            Connect <br>
                          properties:
                            status:
                              type: string
                              x-stoplight:
                                id: u15a41sqiznat
                              enum:
                                - pending
                                - processing
                                - connected
                                - error_no_account_setup
                                - error_permissions
                                - reauth
                                - unknown
                            message:
                              type: string
                              x-stoplight:
                                id: pjjw6f5w5sra5
              examples:
                Success:
                  value:
                    account_id: d8ef1814-5913-492f-b5c0-a16e2d6432c9
                    client_id: 25ea8bd8-f76b-41f9-96e3-1e6162021c50
                    company_id: 87eb4bc3-f76b-35e7-78d2-8f7822021d73
                    products:
                      - company
                      - directory
                    username: johndoe@tryfinch.com
                    payroll_provider_id: gusto
                    manual: 'false'
                    authentication_methods:
                      - type: assisted
                        connection_status:
                          status: pending
                          message: >-
                            This employer has created a token, and we are
                            waiting for access to its provider
                      - type: credential
                        connection_status:
                          status: connected
                          message: This employer is working as expected
      operationId: get-introspect
      description: Read account information associated with an `access_token`
      parameters:
        - $ref: '#/components/parameters/API-Version'
  /disconnect:
    post:
      summary: Disconnect
      operationId: post-disconnect
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: >-
                      If the request is successful, Finch will return “success”
                      (HTTP 200 status).
              examples:
                Success:
                  value:
                    status: success
      description: >-
        Disconnect one or more `access_token`s from your application. Deletion
        is based on both the employer and provider of the `access_token` used to
        call this endpoint, and will also delete all tokens with the same
        employer/provider pair. Other tokens for the same employer, but
        connected to a different provider, require a separate call.

        <br /><br />We require applications to implement the Disconnect endpoint
        for billing and security purposes.
      tags:
        - 4. Management
      parameters:
        - $ref: '#/components/parameters/API-Version'
  /jobs/automated:
    get:
      summary: List All Automated Jobs
      operationId: get-jobs-automated
      description: >-
        Get all automated jobs. Automated jobs are completed by a machine. By
        default, jobs are sorted in descending order by submission time. For
        scheduled jobs such as data syncs, only the next scheduled job is shown.
      parameters:
        - $ref: '#/components/parameters/API-Version'
        - $ref: '#/components/parameters/Content-Type'
      responses:
        '200':
          description: Job was found
          content:
            application/json:
              schema:
                type: object
                properties:
                  '':
                    $ref: '#/components/schemas/Paging'
                    x-stoplight:
                      id: r3x5cv8k9mzrm
                  meta:
                    type: object
                    x-stoplight:
                      id: 1azmf0sda46kp
                    properties:
                      quotas:
                        type: object
                        x-stoplight:
                          id: cyrjsuvgo4yfp
                        description: >-
                          Information about remaining quotas for this
                          connection. Only applicable for customers opted in to
                          use Finch's Data Sync Refresh endpoint (`POST
                          /jobs/automated`). Please contact a Finch
                          representative for more details.
                        properties:
                          data_sync_all:
                            type: object
                            x-stoplight:
                              id: heliy73b0suoc
                            properties:
                              allowed_refreshes:
                                type: integer
                                x-stoplight:
                                  id: rfvybbbqzxuye
                              remaining_refreshes:
                                type: integer
                                x-stoplight:
                                  id: gg9vh14p7m3z3
                  data:
                    type: array
                    x-stoplight:
                      id: choheuhhko7pu
                    items:
                      $ref: '#/components/schemas/AutomatedAsyncJob'
                      x-stoplight:
                        id: gaxb3wl3umjse
                required: []
              examples:
                Example 1:
                  value:
                    '':
                      count: 10
                      offset: 0
                    meta:
                      quotas:
                        data_sync_all:
                          allowed_refreshes: 2
                          remaining_refreshes: 2
                    data:
                      - job_id: 453bd7d7-5355-4d6d-a38e-d9e7eb218c3f
                        job_url: >-
                          https://api.tryfinch.com/job/automated/453bd7d7-5355-4d6d-a38e-d9e7eb218c3f
                        type: data_sync_all
                        status: pending
                        created_at: '2019-08-24T14:15:22Z'
                        scheduled_at: '2019-08-24T14:15:22Z'
                        started_at: '2019-08-24T14:15:22Z'
                        completed_at: '2019-08-24T14:15:22Z'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  status:
                    type: integer
                  code:
                    type: integer
                  name:
                    type: string
                  message:
                    type: string
              examples:
                Example 1:
                  value:
                    statusCode: 401
                    status: 401
                    code: 401
                    message: 'Unauthorized request: no authentication given'
                    name: unauthorized_request_error
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  status:
                    type: integer
                  code:
                    type: integer
                  name:
                    type: string
                  message:
                    type: string
              examples:
                Example 1:
                  value:
                    statusCode: 404
                    status: 404
                    code: 404
                    message: >-
                      could not find job with id
                      job-fb3b25dc-02dc-48eb-9cfc-3f9837276884
                    name: not_found_error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                limit:
                  type: integer
                  x-stoplight:
                    id: ma9qbqvnyzd45
                  description: The number of items to return. Defaults to 100.
                offset:
                  type: integer
                  x-stoplight:
                    id: ecl0kzfvns278
                  description: >-
                    Where in the list of jobs to start returning from. Defaults
                    to index 0.
        description: ''
    post:
      summary: Enqueue a New Automated Job
      operationId: post-jobs-automated
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  job_id:
                    type: string
                    format: uuid
                    description: The id of the job that has been created.
                  job_url:
                    type: string
                    x-stoplight:
                      id: takh9u7o862k5
                    description: The url that can be used to retrieve the job status
                  allowed_refreshes:
                    type: integer
                    description: >-
                      The number of allowed refreshes per hour (per hour, fixed
                      window)
                  remaining_refreshes:
                    type: integer
                    description: >-
                      The number of remaining refreshes available (per hour,
                      fixed window)
              examples:
                Example 1:
                  value:
                    job_id: 453bd7d7-5355-4d6d-a38e-d9e7eb218c3f
                    job_url: >-
                      https://api.tryfinch.com/jobs/automated/453bd7d7-5355-4d6d-a38e-d9e7eb218c3f
                    allowed_refreshes: 2
                    remaining_refreshes: 1
            application/xml:
              schema:
                type: object
                properties: {}
        '202':
          description: >-
            Accepted. This response will be returned if a job is already
            enqueued for the connection. This case does not consume any job
            quota as it just returns the details of an existing job.
          content:
            application/json:
              schema:
                type: object
                properties:
                  job_id:
                    type: string
                    format: uuid
                    x-stoplight:
                      id: po77vhm5eksc0
                    description: The id of the job that has been created.
                  job_url:
                    type: string
                    x-stoplight:
                      id: i6kolzhowzfcl
                    description: The url that can be used to retrieve the job status
                  allowed_refreshes:
                    type: integer
                    description: >-
                      The number of allowed refreshes per hour (per hour, fixed
                      window)
                  remaining_refreshes:
                    type: integer
                    description: >-
                      The number of remaining refreshes available (per hour,
                      fixed window)
              examples:
                Example 1:
                  value:
                    job_Id: de9113d6-e2fa-4c72-ba4a-ee1d8a4f8df6
                    allowed_refreshes: 2
                    remaining_refreshes: 2
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  status:
                    type: integer
                  code:
                    type: integer
                  message:
                    type: string
                  name:
                    type: string
              examples:
                Example 1:
                  value:
                    statusCode: 400
                    status: 400
                    code: 400
                    message: cannot create automated job for Assisted Connect token
                    name: bad_request
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                  status:
                    type: integer
                  code:
                    type: integer
                  name:
                    type: string
                  message:
                    type: string
              examples:
                Example 1:
                  value:
                    statusCode: 401
                    status: 401
                    code: 401
                    message: 'Unauthorized request: no authentication given'
                    name: unauthorized_request_error
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                type: object
                properties:
                  allowed_refreshes:
                    type: integer
                    description: >-
                      The number of allowed refreshes per hour (per hour, fixed
                      window)
                  remaining_refreshes:
                    type: integer
                    description: >-
                      The number of remaining refreshes available (per hour,
                      fixed window)
                  retry_at:
                    type: string
                    format: date-time
                    description: >-
                      The datetime when quota for enqueuing new jobs will again
                      be available. Only shown for a 429 response.
              examples:
                Example 1:
                  value:
                    allowed_refreshes: 2
                    remaining_refreshes: 0
                    retry_at: '2019-08-24T14:15:22Z'
      parameters:
        - $ref: '#/components/parameters/API-Version'
        - $ref: '#/components/parameters/Content-Type'
      description: >-
        Enqueue an automated job. Currently, only the `data-sync-all` job type
        is supported, which will enqueue a job to re-sync all data for a
        connection. `data-sync-all` has a concurrency limit of 1 job at a time
        per connection. This means that if this endpoint is called while a job
        is already in progress for this connection, Finch will return the
        `job_id` of the job that is currently in progress. Finch allows a fixed
        window rate limit of 1 forced refresh per hour per connection.


        This endpoint is available for *Scale* tier customers as an add-on. To
        request access to this endpoint, please contact your Finch account
        manager.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  description: >-
                    The type of job to start. Currently the only supported type
                    is `data_sync_all`
                  enum:
                    - data-sync-all
              required:
                - type
          application/xml:
            schema:
              type: object
              properties: {}
  '/jobs/automated/{job_id}':
    parameters:
      - schema:
          type: string
        name: job_id
        in: path
        required: true
    get:
      summary: Retrieve an Automated Job
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AutomatedAsyncJob'
              examples:
                Example 1:
                  value:
                    job_id: 453bd7d7-5355-4d6d-a38e-d9e7eb218c3f
                    job_url: >-
                      https://api.tryfinch.com/job/automated/453bd7d7-5355-4d6d-a38e-d9e7eb218c3f
                    type: data_sync_all
                    status: pending
                    created_at: '2019-08-24T14:15:22Z'
                    scheduled_at: '2019-08-24T14:15:22Z'
                    started_at: '2019-08-24T14:15:22Z'
                    completed_at: '2019-08-24T14:15:22Z'
        '404':
          description: Not Found
      operationId: get-jobs-job_id
      parameters:
        - $ref: '#/components/parameters/API-Version'
        - $ref: '#/components/parameters/Content-Type'
      description: Get an automated job by `job_id`.
  '/jobs/manual/{job_id}':
    parameters:
      - schema:
          type: string
        name: job_id
        in: path
        required: true
    get:
      summary: Retrieve a Manual Job
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ManualAsyncJob'
              examples:
                Example 1:
                  value:
                    job_id: 497d98f3-580a-4ab9-830a-af2346d029b2
                    status: complete
                    body:
                      - individual_id: 430f9d95-1dcf-4b99-b616-45f814416890
                        code: 201
                        message: Successfully enrolled individual in benefit
                      - individual_id: 647975ac-1e0f-4e9c-b705-e3042da48581
                        code: 200
                        message: Successfully updated enrollment for individual
                      - individual_id: 4a0a3b15-d3d6-41c2-a4a4-ca4ed1b68cf8
                        code: 404
                        message: Individual not found
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  finch_code:
                    type: string
                  name:
                    type: string
                  message:
                    type: string
              examples:
                Example 1:
                  value:
                    code: 400
                    name: invalid_request_error
                    message: job_id is required
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  finch_code:
                    type: string
                  name:
                    type: string
                  message:
                    type: string
              examples:
                Example 1:
                  value:
                    code: 404
                    finch_code: item_not_found
                    name: not_found_error
                    message: >-
                      could not find job with id
                      '49142223-78e0-4092-80e1-313f510b0977'
      operationId: get-jobs-manual-job_id
      description: >-
        Get a manual job by `job_id`. Manual jobs are completed by a human and
        include Assisted Benefits jobs.
      parameters:
        - $ref: '#/components/parameters/API-Version'
        - $ref: '#/components/parameters/Content-Type'
components:
  schemas:
    Paging:
      title: Paging
      type: object
      properties:
        count:
          type: integer
          description: >-
            The total number of elements for the entire query (not just the
            given page)
        offset:
          type: integer
          description: The current start index of the returned list of elements
      x-tags:
        - Models
    Date:
      type: string
      title: Date
      pattern: '([12]\d{3}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01]))'
      nullable: true
    BenefitType:
      type: string
      title: BenefitType
      enum:
        - 401k
        - 401k_roth
        - 401k_loan
        - 403b
        - 403b_roth
        - '457'
        - 457_roth
        - s125_medical
        - s125_dental
        - s125_vision
        - hsa_pre
        - hsa_post
        - fsa_medical
        - fsa_dependent_care
        - simple_ira
        - simple
        - commuter
        - custom_post_tax
        - custom_pre_tax
        - null
      description: Type of benefit.
      x-tags:
        - Models
      nullable: true
    BenefitFrequency:
      type: string
      title: BenefitFrequency
      enum:
        - one_time
        - every_paycheck
      x-tags:
        - Models
      nullable: true
    BenefitContribution:
      title: BenefitContribution
      type: object
      x-tags:
        - Models
      x-examples: {}
      nullable: true
      properties:
        type:
          type: string
          enum:
            - fixed
            - percent
          description: Contribution type.
          nullable: true
        amount:
          type: integer
          description: >-
            Contribution amount in cents (if `fixed`) or basis points (if
            `percent`).
          nullable: true
    BenefitFeature:
      title: BenefitFeature
      type: object
      properties:
        description:
          type: string
          nullable: true
        frequencies:
          type: array
          description: The list of frequencies supported by the provider for this benefit
          items:
            $ref: '#/components/schemas/BenefitFrequency'
        employee_deduction:
          type: array
          description: >-
            Supported deduction types. An empty array indicates deductions are
            not supported.
          nullable: true
          items:
            type: string
            enum:
              - fixed
              - percent
        company_contribution:
          type: array
          description: >-
            Supported contribution types. An empty array indicates contributions
            are not supported.
          nullable: true
          items:
            type: string
            enum:
              - fixed
              - percent
        annual_maximum:
          type: boolean
          description: Whether the provider supports an annual maximum for this benefit.
          nullable: true
        catch_up:
          type: boolean
          description: >-
            Whether the provider supports catch up for this benefit. This field
            will only be true for retirement benefits.
          nullable: true
        hsa_contribution_limit:
          description: >-
            Whether the provider supports HSA contribution limits. Empty if this
            feature is not supported for the benefit. This array only has values
            for HSA benefits.
          type: array
          nullable: true
          items:
            type: string
            enum:
              - individual
              - family
    CompanyBenefit:
      title: CompanyBenefit
      type: object
      properties:
        benefit_id:
          type: string
        type:
          $ref: '#/components/schemas/BenefitType'
        description:
          type: string
          nullable: true
        frequency:
          $ref: '#/components/schemas/BenefitFrequency'
    IndividualBenefits:
      title: IndividualBenefits
      type: array
      x-examples: {}
      items:
        type: object
        properties:
          individual_id:
            type: string
          code:
            type: integer
          body:
            type: object
            properties:
              employee_deduction:
                $ref: '#/components/schemas/BenefitContribution'
              company_contribution:
                $ref: '#/components/schemas/BenefitContribution'
              annual_maximum:
                type: integer
                description: >-
                  If the benefit supports annual maximum, the amount in cents
                  for this individual.
                nullable: true
              catch_up:
                type: boolean
                description: >-
                  If the benefit supports catch up (401k, 403b, etc.), whether
                  catch up is enabled for this individual.
                nullable: true
              hsa_contribution_limit:
                type: string
                enum:
                  - individual
                  - family
                description: Type for HSA contribution limit if the benefit is a HSA.
                nullable: true
    BenefitFeaturesAndOperations:
      type: object
      nullable: true
      properties:
        supported_features:
          $ref: '#/components/schemas/BenefitFeature'
        supported_operations:
          $ref: '#/components/schemas/SupportPerBenefitType'
    BenefitsSupport:
      type: object
      nullable: true
      description: >-
        Each benefit type and their supported features. If the benefit type is
        not supported, the property will be null
      properties:
        '457':
          $ref: '#/components/schemas/BenefitFeaturesAndOperations'
        401k:
          $ref: '#/components/schemas/BenefitFeaturesAndOperations'
        401k_roth:
          $ref: '#/components/schemas/BenefitFeaturesAndOperations'
        401k_loan:
          $ref: '#/components/schemas/BenefitFeaturesAndOperations'
        403b:
          $ref: '#/components/schemas/BenefitFeaturesAndOperations'
        403b_roth:
          $ref: '#/components/schemas/BenefitFeaturesAndOperations'
        457_roth:
          $ref: '#/components/schemas/BenefitFeaturesAndOperations'
        s125_medical:
          $ref: '#/components/schemas/BenefitFeaturesAndOperations'
        s125_dental:
          $ref: '#/components/schemas/BenefitFeaturesAndOperations'
        s125_vision:
          $ref: '#/components/schemas/BenefitFeaturesAndOperations'
        hsa_pre:
          $ref: '#/components/schemas/BenefitFeaturesAndOperations'
        hsa_post:
          $ref: '#/components/schemas/BenefitFeaturesAndOperations'
        fsa_medical:
          $ref: '#/components/schemas/BenefitFeaturesAndOperations'
        fsa_dependent_care:
          $ref: '#/components/schemas/BenefitFeaturesAndOperations'
        simple_ira:
          $ref: '#/components/schemas/BenefitFeaturesAndOperations'
        simple:
          $ref: '#/components/schemas/BenefitFeaturesAndOperations'
        commuter:
          $ref: '#/components/schemas/BenefitFeaturesAndOperations'
        custom_post_tax:
          $ref: '#/components/schemas/BenefitFeaturesAndOperations'
        custom_pre_tax:
          $ref: '#/components/schemas/BenefitFeaturesAndOperations'
      additionalProperties: false
    AuthenticationMethod:
      type: object
      properties:
        type:
          type: string
          description: The type of authentication method.
          enum:
            - assisted
            - credential
            - api_token
            - oauth
        benefits_support:
          $ref: '#/components/schemas/BenefitsSupport'
        supported_fields:
          $ref: '#/components/schemas/SupportedFields'
    SupportedFields:
      type: object
      properties:
        company:
          $ref: '#/components/schemas/SupportedCompanyFields'
        directory:
          $ref: '#/components/schemas/SupportedDirectoryFields'
        individual:
          $ref: '#/components/schemas/SupportedIndividualFields'
        employment:
          $ref: '#/components/schemas/SupportedEmploymentFields'
        payment:
          $ref: '#/components/schemas/SupportedPaymentFields'
        pay_statement:
          $ref: '#/components/schemas/SupportedPayStatementFields'
      nullable: true
    SupportedCompanyFields:
      type: object
      properties:
        id:
          type: boolean
        legal_name:
          type: boolean
        entity:
          type: object
          properties:
            type:
              type: boolean
            subtype:
              type: boolean
        primary_email:
          type: boolean
        primary_phone_number:
          type: boolean
        ein:
          type: boolean
        accounts:
          type: object
          properties:
            routing_number:
              type: boolean
            account_name:
              type: boolean
            institution_name:
              type: boolean
            account_type:
              type: boolean
            account_number:
              type: boolean
        departments:
          type: object
          properties:
            name:
              type: boolean
            parent:
              type: object
              properties:
                name:
                  type: boolean
        locations:
          type: object
          properties:
            line1:
              type: boolean
            line2:
              type: boolean
            city:
              type: boolean
            state:
              type: boolean
            postal_code:
              type: boolean
            country:
              type: boolean
    SupportedDirectoryFields:
      type: object
      properties:
        paging:
          type: object
          properties:
            count:
              type: boolean
            offset:
              type: boolean
        individuals:
          type: object
          properties:
            id:
              type: boolean
            first_name:
              type: boolean
            middle_name:
              type: boolean
            last_name:
              type: boolean
            is_active:
              type: boolean
            department:
              type: boolean
              nullable: true
            manager:
              type: object
              properties:
                id:
                  type: boolean
    SupportedIndividualFields:
      type: object
      properties:
        id:
          type: boolean
        first_name:
          type: boolean
        middle_name:
          type: boolean
        last_name:
          type: boolean
        preferred_name:
          type: boolean
        dob:
          type: boolean
        gender:
          type: boolean
        ethnicity:
          type: boolean
        ssn:
          type: boolean
        emails:
          type: object
          properties:
            data:
              type: boolean
            type:
              type: boolean
        phone_numbers:
          type: object
          properties:
            data:
              type: boolean
            type:
              type: boolean
        residence:
          type: object
          properties:
            city:
              type: boolean
            country:
              type: boolean
            line1:
              type: boolean
            line2:
              type: boolean
            postal_code:
              type: boolean
            state:
              type: boolean
    SupportedEmploymentFields:
      type: object
      properties:
        id:
          type: boolean
        first_name:
          type: boolean
        middle_name:
          type: boolean
        last_name:
          type: boolean
        title:
          type: boolean
        start_date:
          type: boolean
        end_date:
          type: boolean
        is_active:
          type: boolean
        income_history:
          type: boolean
        class_code:
          type: boolean
        custom_fields:
          type: boolean
        department:
          type: object
          properties:
            name:
              type: boolean
        employment:
          type: object
          properties:
            type:
              type: boolean
            subtype:
              type: boolean
        income:
          type: object
          properties:
            amount:
              type: boolean
            currency:
              type: boolean
            unit:
              type: boolean
        location:
          type: object
          properties:
            line1:
              type: boolean
            line2:
              type: boolean
            city:
              type: boolean
            state:
              type: boolean
            postal_code:
              type: boolean
            country:
              type: boolean
        manager:
          type: boolean
          nullable: true
    SupportedPaymentFields:
      type: object
      properties:
        id:
          type: boolean
        pay_date:
          type: boolean
        debit_date:
          type: boolean
        company_debit:
          type: boolean
        gross_pay:
          type: boolean
        net_pay:
          type: boolean
        employer_taxes:
          type: boolean
        employee_taxes:
          type: boolean
        individual_ids:
          type: boolean
        pay_period:
          type: object
          properties:
            start_date:
              type: boolean
            end_date:
              type: boolean
    SupportedPayStatementFields:
      type: object
      properties:
        paging:
          type: object
          properties:
            count:
              type: boolean
            offset:
              type: boolean
          required:
            - count
            - offset
        pay_statements:
          type: object
          properties:
            individual_id:
              type: boolean
            type:
              type: boolean
            payment_method:
              type: boolean
            total_hours:
              type: boolean
            gross_pay:
              type: boolean
            net_pay:
              type: boolean
            earnings:
              type: object
              properties:
                type:
                  type: boolean
                name:
                  type: boolean
                amount:
                  type: boolean
                currency:
                  type: boolean
            employee_deductions:
              type: object
              properties:
                name:
                  type: boolean
                amount:
                  type: boolean
                type:
                  type: boolean
                pre_tax:
                  type: boolean
                currency:
                  type: boolean
            employer_deductions:
              type: object
              properties:
                name:
                  type: boolean
                amount:
                  type: boolean
                currency:
                  type: boolean
            taxes:
              type: object
              properties:
                type:
                  type: boolean
                name:
                  type: boolean
                employer:
                  type: boolean
                amount:
                  type: boolean
                currency:
                  type: boolean
    OperationSupport:
      type: string
      enum:
        - supported
        - not_supported_by_finch
        - not_supported_by_provider
        - client_access_only
      description: >
        - `supported`: This operation is supported by both the provider and
        Finch <br>

        - `not_supported_by_finch`: This operation is not supported by Finch but
        supported by the provider <br>

        - `not_supported_by_provider`: This operation is not supported by the
        provider, so Finch cannot support <br>

        - `client_access_only`: This behavior is supported by the provider, but
        only available to the client and not to Finch
    OperationSupportMatrix:
      type: object
      properties:
        create:
          $ref: '#/components/schemas/OperationSupport'
        update:
          $ref: '#/components/schemas/OperationSupport'
        delete:
          $ref: '#/components/schemas/OperationSupport'
        read:
          $ref: '#/components/schemas/OperationSupport'
    SupportPerBenefitType:
      type: object
      title: SupportPerBenefitType
      properties:
        company_benefits:
          $ref: '#/components/schemas/OperationSupportMatrix'
        individual_benefits:
          $ref: '#/components/schemas/OperationSupportMatrix'
    Error:
      title: Error
      type: object
      description: Generic error response structure
      properties:
        code:
          type: integer
          description: The status code of the request.
        name:
          type: string
          description: Identifier describing the error.
        finch_code:
          type: string
          description: A descriptive identifier for the error.
        message:
          type: string
          description: >-
            A short English description that provides more information about the
            error.
      x-examples:
        not-found-error:
          code: 404
          name: not_found_error
          finch_code: individual_not_found
          message: Individual not found for benefit
    AutomatedAsyncJob:
      title: AutomatedAsyncJob
      x-stoplight:
        id: a7x0jx1utnuc8
      type: object
      x-examples:
        Example 1:
          job_id: job-7e8d96ab-898f-4495-8b74-6316bb30b772
          type: scheduled
          code: 200
          created_at: '2019-08-24T14:15:22Z'
          started_at: '2019-08-24T14:15:22Z'
          completed_at: '2019-08-24T14:15:22Z'
      properties:
        job_id:
          type: string
          description: The id of the job that has been created.
          format: uuid
        job_url:
          type: string
          x-stoplight:
            id: 458kw0otrh80f
          description: The url that can be used to retrieve the job status
        type:
          type: string
          description: Only `data_sync_all` currently supported
          enum:
            - data_sync_all
        status:
          type: string
          x-stoplight:
            id: gms9h3qps1fww
          enum:
            - pending
            - in_progress
            - complete
            - error
            - reauth_error
            - permissions_error
        created_at:
          type: string
          format: date-time
          description: >-
            The datetime when the job was created. for scheduled jobs, this will
            be the initial connection time. For ad-hoc jobs, this will be the
            time the creation request was received.
        scheduled_at:
          type: string
          x-stoplight:
            id: 4r3jtdvecoqw2
          format: date-time
          description: "The datetime a job is scheduled to be run. For scheduled jobs, this datetime can be in the future if the job has not yet been enqueued. For ad-hoc jobs, this field will be\_null."
          nullable: true
        started_at:
          type: string
          format: date-time
          description: The datetime a job entered into the job queue.
          nullable: true
        completed_at:
          type: string
          format: date-time
          description: The datetime the job completed.
          nullable: true
    ManualAsyncJob:
      title: ManualAsyncJob
      x-stoplight:
        id: vddn2z8jbg1c6
      type: object
      x-examples:
        Example 1:
          job_id: 453bd7d7-5355-4d6d-a38e-d9e7eb218c3f
          status: complete
          body:
            - individual_id: 46decc95-451e-44ef-baac-b228d778267f
              message: Successfully updated benefit for individual
      properties:
        job_id:
          type: string
          format: uuid
        status:
          type: string
          enum:
            - pending
            - in_progress
            - error
            - complete
        body:
          type: array
          description: >-
            Specific information about the job, such as individual statuses for
            batch jobs.
          nullable: true
          items: {}
  requestBodies:
    Individual-Ids:
      content:
        application/json:
          schema:
            type: object
            description: Individual Ids Request Body
            properties:
              requests:
                type: array
                description: The array of batch requests.
                items:
                  type: object
                  properties:
                    individual_id:
                      type: string
                      description: >-
                        A stable Finch `id` (UUID v4) for an individual in the
                        company. There is no limit to the number of
                        `individual_id` to send per request. It is preferential
                        to send all ids in a single request for Finch to
                        optimize provider rate-limits.
                  required:
                    - individual_id
            required:
              - requests
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      description: Please use your Access Token
  parameters:
    API-Version:
      name: Finch-API-Version
      in: header
      required: true
      schema:
        type: string
        default: '2020-09-17'
        format: date
        pattern: YYYY-MM-DD
      description: >-
        Header used to specify the version for a given API request. Current
        version is 2020-09-17.
    Content-Type:
      name: Content-Type
      in: header
      required: true
      schema:
        type: string
        default: application/json
      description: 'Used to indicate the original media type of the resource '
security:
  - bearerAuth: []